### PR TITLE
Add IPolyglot

### PR DESCRIPTION
**Pull request by fniephaus**

### CODE REVIEW

**Comment by neomatrix369** [comment]
Awesome share @fniephaus do you have worked out examples/videos/code snippets to show how to install and use it?

**Comment by fniephaus** [comment]
Everything you need should be in the README.md. Otherwise, it's a bug. ;)

**Comment by neomatrix369** [comment]
> Everything you need should be in the README.md. Otherwise, it's a bug. ;)

If I find any bug(s) I will try to help fix them, or otherwise let you know!

Best way to find out is use it!

**Comment by fniephaus** [comment]
Please do! :)

**Pull request merged**
